# Generated by Django 2.0.13 on 2020-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtime_timestamp', models.CharField(max_length=20)),
                ('monolithic_timestamp', models.CharField(max_length=20)),
                ('utc', models.CharField(max_length=20)),
                ('master_offset', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('path_delay', models.IntegerField()),
            ],
        ),
    ]
